"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from datetime import date, datetime
from permitstack import errors, models, utils
from permitstack._hooks import HookContext
from permitstack.types import OptionalNullable, UNSET
from permitstack.utils import get_security_from_env
from permitstack.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional


class Permits(BaseSDK):
    r"""Search and retrieve building permits"""

    def search_permits(
        self,
        *,
        zip_code: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        address: OptionalNullable[str] = UNSET,
        lat: OptionalNullable[float] = UNSET,
        lng: OptionalNullable[float] = UNSET,
        radius_miles: Optional[float] = 5,
        bbox: OptionalNullable[str] = UNSET,
        polygon: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        status: OptionalNullable[models.PermitStatus] = UNSET,
        property_type: OptionalNullable[models.PropertyType] = UNSET,
        tag: OptionalNullable[str] = UNSET,
        record_kind: Optional[str] = "permit",
        filed_after: OptionalNullable[date] = UNSET,
        filed_before: OptionalNullable[date] = UNSET,
        issued_after: OptionalNullable[date] = UNSET,
        issued_before: OptionalNullable[date] = UNSET,
        date_after: OptionalNullable[date] = UNSET,
        date_before: OptionalNullable[date] = UNSET,
        parcel: OptionalNullable[str] = UNSET,
        min_value: OptionalNullable[float] = UNSET,
        max_value: OptionalNullable[float] = UNSET,
        min_solar_kw: OptionalNullable[float] = UNSET,
        max_solar_kw: OptionalNullable[float] = UNSET,
        min_sqft: OptionalNullable[float] = UNSET,
        has_enrichment: OptionalNullable[bool] = UNSET,
        scope: OptionalNullable[str] = UNSET,
        q: OptionalNullable[str] = UNSET,
        contractor_name: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Search Permits

        :param zip_code: 5-digit ZIP code
        :param city: City name
        :param state: 2-letter state code
        :param jurisdiction: Jurisdiction name (e.g. 'Wake County', 'Tacoma') or partial match
        :param address: Street address, partial + case-insensitive (e.g. '1600 Pennsylvania') — indexed, fast
        :param lat: Latitude for radius search
        :param lng: Longitude for radius search
        :param radius_miles: Radius in miles (used with lat/lng)
        :param bbox: Map-viewport bounding box 'minLng,minLat,maxLng,maxLat'. Returns permits whose location falls inside the box (geocoded permits only).
        :param polygon: A drawn area as a GeoJSON Polygon geometry (URL-encoded), e.g. {\"type\":\"Polygon\",\"coordinates\":[[[lng,lat],...]]}. Returns permits inside the polygon (geocoded permits only).
        :param category: Permit category (e.g. solar, SOLAR, roofing, hvac — case insensitive)
        :param status: Permit status (e.g. issued, filed, final)
        :param property_type: Property type (e.g. residential, commercial)
        :param tag: Filter by tag
        :param record_kind: Record kind: 'permit' (default, building permits only), 'contractor', 'tag', 'non_building', 'admin', or 'all'
        :param filed_after: Filed on or after this date
        :param filed_before: Filed on or before this date
        :param issued_after: Issued on or after this date
        :param issued_before: Issued on or before this date
        :param date_after: On or after this date, matched against whichever date a record has (issued, else filed). Use this when a source populates only one of issued/filed — e.g. issued-only feeds vs filed-only feeds.
        :param date_before: On or before this date, matched against whichever date a record has (issued, else filed).
        :param parcel: Parcel number / APN / folio (formatting ignored). Returns permits on that parcel where the source publishes one.
        :param min_value: Minimum estimated value
        :param max_value: Maximum estimated value
        :param min_solar_kw: Minimum extracted solar system size (kW DC)
        :param max_solar_kw: Maximum extracted solar system size (kW DC)
        :param min_sqft: Minimum square footage mentioned (from enrichment)
        :param has_enrichment: Only permits that have (true) or lack (false) LLM enrichment
        :param scope: Substring match on the enriched work scope
        :param q: Case-insensitive substring match across description, address, and permit number
        :param contractor_name: Contractor name (partial match)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SearchPermitsRequest(
            zip_code=zip_code,
            city=city,
            state=state,
            jurisdiction=jurisdiction,
            address=address,
            lat=lat,
            lng=lng,
            radius_miles=radius_miles,
            bbox=bbox,
            polygon=polygon,
            category=category,
            status=status,
            property_type=property_type,
            tag=tag,
            record_kind=record_kind,
            filed_after=filed_after,
            filed_before=filed_before,
            issued_after=issued_after,
            issued_before=issued_before,
            date_after=date_after,
            date_before=date_before,
            parcel=parcel,
            min_value=min_value,
            max_value=max_value,
            min_solar_kw=min_solar_kw,
            max_solar_kw=max_solar_kw,
            min_sqft=min_sqft,
            has_enrichment=has_enrichment,
            scope=scope,
            q=q,
            contractor_name=contractor_name,
            page=page,
            per_page=per_page,
        )

        req = self._build_request(
            method="GET",
            path="/v1/permits/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search_permits",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def search_permits_async(
        self,
        *,
        zip_code: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        address: OptionalNullable[str] = UNSET,
        lat: OptionalNullable[float] = UNSET,
        lng: OptionalNullable[float] = UNSET,
        radius_miles: Optional[float] = 5,
        bbox: OptionalNullable[str] = UNSET,
        polygon: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        status: OptionalNullable[models.PermitStatus] = UNSET,
        property_type: OptionalNullable[models.PropertyType] = UNSET,
        tag: OptionalNullable[str] = UNSET,
        record_kind: Optional[str] = "permit",
        filed_after: OptionalNullable[date] = UNSET,
        filed_before: OptionalNullable[date] = UNSET,
        issued_after: OptionalNullable[date] = UNSET,
        issued_before: OptionalNullable[date] = UNSET,
        date_after: OptionalNullable[date] = UNSET,
        date_before: OptionalNullable[date] = UNSET,
        parcel: OptionalNullable[str] = UNSET,
        min_value: OptionalNullable[float] = UNSET,
        max_value: OptionalNullable[float] = UNSET,
        min_solar_kw: OptionalNullable[float] = UNSET,
        max_solar_kw: OptionalNullable[float] = UNSET,
        min_sqft: OptionalNullable[float] = UNSET,
        has_enrichment: OptionalNullable[bool] = UNSET,
        scope: OptionalNullable[str] = UNSET,
        q: OptionalNullable[str] = UNSET,
        contractor_name: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Search Permits

        :param zip_code: 5-digit ZIP code
        :param city: City name
        :param state: 2-letter state code
        :param jurisdiction: Jurisdiction name (e.g. 'Wake County', 'Tacoma') or partial match
        :param address: Street address, partial + case-insensitive (e.g. '1600 Pennsylvania') — indexed, fast
        :param lat: Latitude for radius search
        :param lng: Longitude for radius search
        :param radius_miles: Radius in miles (used with lat/lng)
        :param bbox: Map-viewport bounding box 'minLng,minLat,maxLng,maxLat'. Returns permits whose location falls inside the box (geocoded permits only).
        :param polygon: A drawn area as a GeoJSON Polygon geometry (URL-encoded), e.g. {\"type\":\"Polygon\",\"coordinates\":[[[lng,lat],...]]}. Returns permits inside the polygon (geocoded permits only).
        :param category: Permit category (e.g. solar, SOLAR, roofing, hvac — case insensitive)
        :param status: Permit status (e.g. issued, filed, final)
        :param property_type: Property type (e.g. residential, commercial)
        :param tag: Filter by tag
        :param record_kind: Record kind: 'permit' (default, building permits only), 'contractor', 'tag', 'non_building', 'admin', or 'all'
        :param filed_after: Filed on or after this date
        :param filed_before: Filed on or before this date
        :param issued_after: Issued on or after this date
        :param issued_before: Issued on or before this date
        :param date_after: On or after this date, matched against whichever date a record has (issued, else filed). Use this when a source populates only one of issued/filed — e.g. issued-only feeds vs filed-only feeds.
        :param date_before: On or before this date, matched against whichever date a record has (issued, else filed).
        :param parcel: Parcel number / APN / folio (formatting ignored). Returns permits on that parcel where the source publishes one.
        :param min_value: Minimum estimated value
        :param max_value: Maximum estimated value
        :param min_solar_kw: Minimum extracted solar system size (kW DC)
        :param max_solar_kw: Maximum extracted solar system size (kW DC)
        :param min_sqft: Minimum square footage mentioned (from enrichment)
        :param has_enrichment: Only permits that have (true) or lack (false) LLM enrichment
        :param scope: Substring match on the enriched work scope
        :param q: Case-insensitive substring match across description, address, and permit number
        :param contractor_name: Contractor name (partial match)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SearchPermitsRequest(
            zip_code=zip_code,
            city=city,
            state=state,
            jurisdiction=jurisdiction,
            address=address,
            lat=lat,
            lng=lng,
            radius_miles=radius_miles,
            bbox=bbox,
            polygon=polygon,
            category=category,
            status=status,
            property_type=property_type,
            tag=tag,
            record_kind=record_kind,
            filed_after=filed_after,
            filed_before=filed_before,
            issued_after=issued_after,
            issued_before=issued_before,
            date_after=date_after,
            date_before=date_before,
            parcel=parcel,
            min_value=min_value,
            max_value=max_value,
            min_solar_kw=min_solar_kw,
            max_solar_kw=max_solar_kw,
            min_sqft=min_sqft,
            has_enrichment=has_enrichment,
            scope=scope,
            q=q,
            contractor_name=contractor_name,
            page=page,
            per_page=per_page,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/permits/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search_permits",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def export_permits(
        self,
        *,
        zip_code: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        status: OptionalNullable[models.PermitStatus] = UNSET,
        property_type: OptionalNullable[models.PropertyType] = UNSET,
        tag: OptionalNullable[str] = UNSET,
        record_kind: Optional[str] = "permit",
        filed_after: OptionalNullable[date] = UNSET,
        filed_before: OptionalNullable[date] = UNSET,
        issued_after: OptionalNullable[date] = UNSET,
        issued_before: OptionalNullable[date] = UNSET,
        date_after: OptionalNullable[date] = UNSET,
        date_before: OptionalNullable[date] = UNSET,
        parcel: OptionalNullable[str] = UNSET,
        min_value: OptionalNullable[float] = UNSET,
        max_value: OptionalNullable[float] = UNSET,
        min_solar_kw: OptionalNullable[float] = UNSET,
        max_solar_kw: OptionalNullable[float] = UNSET,
        min_sqft: OptionalNullable[float] = UNSET,
        has_enrichment: OptionalNullable[bool] = UNSET,
        scope: OptionalNullable[str] = UNSET,
        q: OptionalNullable[str] = UNSET,
        contractor_name: OptionalNullable[str] = UNSET,
        limit: Optional[int] = 1000,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Export Permits

        Export permits matching filters as CSV. Tier-gated row limits.

        :param zip_code:
        :param city:
        :param state:
        :param category:
        :param status:
        :param property_type:
        :param tag:
        :param record_kind:
        :param filed_after:
        :param filed_before:
        :param issued_after:
        :param issued_before:
        :param date_after: On or after this date, matched against whichever date a record has (issued, else filed).
        :param date_before: On or before this date, matched against whichever date a record has (issued, else filed).
        :param parcel: Parcel number / APN / folio (formatting ignored).
        :param min_value:
        :param max_value:
        :param min_solar_kw:
        :param max_solar_kw:
        :param min_sqft:
        :param has_enrichment:
        :param scope:
        :param q:
        :param contractor_name:
        :param limit:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ExportPermitsRequest(
            zip_code=zip_code,
            city=city,
            state=state,
            category=category,
            status=status,
            property_type=property_type,
            tag=tag,
            record_kind=record_kind,
            filed_after=filed_after,
            filed_before=filed_before,
            issued_after=issued_after,
            issued_before=issued_before,
            date_after=date_after,
            date_before=date_before,
            parcel=parcel,
            min_value=min_value,
            max_value=max_value,
            min_solar_kw=min_solar_kw,
            max_solar_kw=max_solar_kw,
            min_sqft=min_sqft,
            has_enrichment=has_enrichment,
            scope=scope,
            q=q,
            contractor_name=contractor_name,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/v1/permits/export",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="export_permits",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def export_permits_async(
        self,
        *,
        zip_code: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        status: OptionalNullable[models.PermitStatus] = UNSET,
        property_type: OptionalNullable[models.PropertyType] = UNSET,
        tag: OptionalNullable[str] = UNSET,
        record_kind: Optional[str] = "permit",
        filed_after: OptionalNullable[date] = UNSET,
        filed_before: OptionalNullable[date] = UNSET,
        issued_after: OptionalNullable[date] = UNSET,
        issued_before: OptionalNullable[date] = UNSET,
        date_after: OptionalNullable[date] = UNSET,
        date_before: OptionalNullable[date] = UNSET,
        parcel: OptionalNullable[str] = UNSET,
        min_value: OptionalNullable[float] = UNSET,
        max_value: OptionalNullable[float] = UNSET,
        min_solar_kw: OptionalNullable[float] = UNSET,
        max_solar_kw: OptionalNullable[float] = UNSET,
        min_sqft: OptionalNullable[float] = UNSET,
        has_enrichment: OptionalNullable[bool] = UNSET,
        scope: OptionalNullable[str] = UNSET,
        q: OptionalNullable[str] = UNSET,
        contractor_name: OptionalNullable[str] = UNSET,
        limit: Optional[int] = 1000,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Export Permits

        Export permits matching filters as CSV. Tier-gated row limits.

        :param zip_code:
        :param city:
        :param state:
        :param category:
        :param status:
        :param property_type:
        :param tag:
        :param record_kind:
        :param filed_after:
        :param filed_before:
        :param issued_after:
        :param issued_before:
        :param date_after: On or after this date, matched against whichever date a record has (issued, else filed).
        :param date_before: On or before this date, matched against whichever date a record has (issued, else filed).
        :param parcel: Parcel number / APN / folio (formatting ignored).
        :param min_value:
        :param max_value:
        :param min_solar_kw:
        :param max_solar_kw:
        :param min_sqft:
        :param has_enrichment:
        :param scope:
        :param q:
        :param contractor_name:
        :param limit:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ExportPermitsRequest(
            zip_code=zip_code,
            city=city,
            state=state,
            category=category,
            status=status,
            property_type=property_type,
            tag=tag,
            record_kind=record_kind,
            filed_after=filed_after,
            filed_before=filed_before,
            issued_after=issued_after,
            issued_before=issued_before,
            date_after=date_after,
            date_before=date_before,
            parcel=parcel,
            min_value=min_value,
            max_value=max_value,
            min_solar_kw=min_solar_kw,
            max_solar_kw=max_solar_kw,
            min_sqft=min_sqft,
            has_enrichment=has_enrichment,
            scope=scope,
            q=q,
            contractor_name=contractor_name,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/permits/export",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="export_permits",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def list_permit_events(
        self,
        *,
        event_type: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        permit_id: OptionalNullable[str] = UNSET,
        detected_after: OptionalNullable[datetime] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitEventsResponse:
        r"""List Permit Events

        Queryable feed of permit status/date transitions (new_permit, status_change,
        issued, completed, expired), built from a daily-ingest diff. A real-time,
        historical, filter-scoped change feed no competitor offers below enterprise —
        pair it with a webhook to be alerted the moment a matching permit changes status.

        :param event_type: Filter by event type: new_permit, status_change, issued, completed, expired
        :param category: Permit category (e.g. solar, battery)
        :param city: City name
        :param state: 2-letter state code
        :param jurisdiction: Jurisdiction name (partial)
        :param permit_id: Events for a single permit id
        :param detected_after: Only events detected on/after this UTC timestamp (ISO 8601)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListPermitEventsRequest(
            event_type=event_type,
            category=category,
            city=city,
            state=state,
            jurisdiction=jurisdiction,
            permit_id=permit_id,
            detected_after=detected_after,
            page=page,
            per_page=per_page,
        )

        req = self._build_request(
            method="GET",
            path="/v1/permits/events",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_permit_events",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitEventsResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def list_permit_events_async(
        self,
        *,
        event_type: OptionalNullable[str] = UNSET,
        category: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        state: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        permit_id: OptionalNullable[str] = UNSET,
        detected_after: OptionalNullable[datetime] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitEventsResponse:
        r"""List Permit Events

        Queryable feed of permit status/date transitions (new_permit, status_change,
        issued, completed, expired), built from a daily-ingest diff. A real-time,
        historical, filter-scoped change feed no competitor offers below enterprise —
        pair it with a webhook to be alerted the moment a matching permit changes status.

        :param event_type: Filter by event type: new_permit, status_change, issued, completed, expired
        :param category: Permit category (e.g. solar, battery)
        :param city: City name
        :param state: 2-letter state code
        :param jurisdiction: Jurisdiction name (partial)
        :param permit_id: Events for a single permit id
        :param detected_after: Only events detected on/after this UTC timestamp (ISO 8601)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListPermitEventsRequest(
            event_type=event_type,
            category=category,
            city=city,
            state=state,
            jurisdiction=jurisdiction,
            permit_id=permit_id,
            detected_after=detected_after,
            page=page,
            per_page=per_page,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/permits/events",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_permit_events",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitEventsResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def get_permit(
        self,
        *,
        permit_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitDetail:
        r"""Get Permit

        Get full details for a single permit.

        :param permit_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPermitRequest(
            permit_id=permit_id,
        )

        req = self._build_request(
            method="GET",
            path="/v1/permits/{permit_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permit",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitDetail, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def get_permit_async(
        self,
        *,
        permit_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitDetail:
        r"""Get Permit

        Get full details for a single permit.

        :param permit_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPermitRequest(
            permit_id=permit_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/permits/{permit_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permit",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitDetail, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def get_permits_by_address(
        self,
        *,
        address: str,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Get Permits By Address

        Get all permits for a specific address (partial match).

        :param address:
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPermitsByAddressRequest(
            address=address,
            page=page,
            per_page=per_page,
        )

        req = self._build_request(
            method="GET",
            path="/v1/permits/address/{address}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permits_by_address",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def get_permits_by_address_async(
        self,
        *,
        address: str,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Get Permits By Address

        Get all permits for a specific address (partial match).

        :param address:
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPermitsByAddressRequest(
            address=address,
            page=page,
            per_page=per_page,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/permits/address/{address}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_permits_by_address",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def get_coverage_stats(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Get Coverage Stats

        Get coverage statistics — total permits, jurisdictions, and breakdown by city.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/v1/permits/stats/coverage",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_coverage_stats",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def get_coverage_stats_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Get Coverage Stats

        Get coverage statistics — total permits, jurisdictions, and breakdown by city.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/v1/permits/stats/coverage",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_coverage_stats",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def list_plays(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""List Plays

        List available trade plays and their parameters.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/v1/plays",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_plays",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def list_plays_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""List Plays

        List available trade plays and their parameters.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/v1/plays",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="list_plays",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def battery_retrofit_candidates(
        self,
        *,
        state: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        zip_code: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        min_age_years: Optional[float] = 2,
        max_age_years: Optional[float] = 7,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Battery Retrofit Candidates

        Solar permits aged between min/max years whose address has NO battery permit
        on file — the storage-retrofit lead list. Requires a location filter.

        :param state: 2-letter state code
        :param city: City name
        :param zip_code: 5-digit ZIP
        :param jurisdiction: Jurisdiction name (partial)
        :param min_age_years: Minimum age of the PV permit, in years
        :param max_age_years: Maximum age of the PV permit, in years
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.BatteryRetrofitCandidatesRequest(
            state=state,
            city=city,
            zip_code=zip_code,
            jurisdiction=jurisdiction,
            min_age_years=min_age_years,
            max_age_years=max_age_years,
            page=page,
            per_page=per_page,
        )

        req = self._build_request(
            method="GET",
            path="/v1/plays/battery-retrofit-candidates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="battery_retrofit_candidates",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def battery_retrofit_candidates_async(
        self,
        *,
        state: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        zip_code: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        min_age_years: Optional[float] = 2,
        max_age_years: Optional[float] = 7,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Battery Retrofit Candidates

        Solar permits aged between min/max years whose address has NO battery permit
        on file — the storage-retrofit lead list. Requires a location filter.

        :param state: 2-letter state code
        :param city: City name
        :param zip_code: 5-digit ZIP
        :param jurisdiction: Jurisdiction name (partial)
        :param min_age_years: Minimum age of the PV permit, in years
        :param max_age_years: Maximum age of the PV permit, in years
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.BatteryRetrofitCandidatesRequest(
            state=state,
            city=city,
            zip_code=zip_code,
            jurisdiction=jurisdiction,
            min_age_years=min_age_years,
            max_age_years=max_age_years,
            page=page,
            per_page=per_page,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/plays/battery-retrofit-candidates",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="battery_retrofit_candidates",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    def orphan_recovery(
        self,
        *,
        installer: str,
        state: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        zip_code: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Orphan Recovery

        PV permits whose installer (contractor, applicant, or owner) matches `installer`
        in a territory — a named competitor's customer base. Requires a location filter.

        :param installer: Installer name to match (contractor/applicant/owner)
        :param state: 2-letter state code
        :param city: City name
        :param zip_code: 5-digit ZIP
        :param jurisdiction: Jurisdiction name (partial)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OrphanRecoveryRequest(
            installer=installer,
            state=state,
            city=city,
            zip_code=zip_code,
            jurisdiction=jurisdiction,
            page=page,
            per_page=per_page,
        )

        req = self._build_request(
            method="GET",
            path="/v1/plays/orphan-recovery",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="orphan_recovery",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)

    async def orphan_recovery_async(
        self,
        *,
        installer: str,
        state: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        zip_code: OptionalNullable[str] = UNSET,
        jurisdiction: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        per_page: Optional[int] = 25,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PermitSearchResponse:
        r"""Orphan Recovery

        PV permits whose installer (contractor, applicant, or owner) matches `installer`
        in a territory — a named competitor's customer base. Requires a location filter.

        :param installer: Installer name to match (contractor/applicant/owner)
        :param state: 2-letter state code
        :param city: City name
        :param zip_code: 5-digit ZIP
        :param jurisdiction: Jurisdiction name (partial)
        :param page:
        :param per_page:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.OrphanRecoveryRequest(
            installer=installer,
            state=state,
            city=city,
            zip_code=zip_code,
            jurisdiction=jurisdiction,
            page=page,
            per_page=per_page,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/plays/orphan-recovery",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="orphan_recovery",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PermitSearchResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PermitstackDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PermitstackDefaultError("Unexpected response received", http_res)
