"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from permitstack.errors import PermitstackError
from permitstack.types import BaseModel
from typing import Optional


class ErrorDetailData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ErrorDetail(PermitstackError):
    data: ErrorDetailData = field(hash=False)

    def __init__(
        self,
        data: ErrorDetailData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
