"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from permitstack.errors import PermitstackError
from permitstack.models import featurelocked_error as models_featurelocked_error
from permitstack.types import BaseModel
from typing import Optional


class FeatureLockedErrorData(BaseModel):
    detail: Optional[models_featurelocked_error.Detail] = None


@dataclass(unsafe_hash=True)
class FeatureLockedError(PermitstackError):
    data: FeatureLockedErrorData = field(hash=False)

    def __init__(
        self,
        data: FeatureLockedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
