"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from permitstack.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .contractorprofile import ContractorProfile, ContractorProfileTypedDict
    from .contractorsearchresponse import (
        ContractorSearchResponse,
        ContractorSearchResponseTypedDict,
    )
    from .contractorsummary import ContractorSummary, ContractorSummaryTypedDict
    from .delete_webhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .export_permits_csvop import (
        ExportPermitsCsvRequest,
        ExportPermitsCsvRequestTypedDict,
    )
    from .get_contractor_permitsop import (
        GetContractorPermitsRequest,
        GetContractorPermitsRequestTypedDict,
    )
    from .get_contractorop import GetContractorRequest, GetContractorRequestTypedDict
    from .get_permitop import GetPermitRequest, GetPermitRequestTypedDict
    from .get_permits_by_addressop import (
        GetPermitsByAddressRequest,
        GetPermitsByAddressRequestTypedDict,
    )
    from .get_property_historyop import (
        GetPropertyHistoryRequest,
        GetPropertyHistoryRequestTypedDict,
    )
    from .permitcategory import PermitCategory
    from .permitdetail import PermitDetail, PermitDetailTypedDict
    from .permitsearchresponse import (
        PermitSearchResponse,
        PermitSearchResponseTypedDict,
    )
    from .permitstatus import PermitStatus
    from .permitsummary import PermitSummary, PermitSummaryTypedDict
    from .propertytype import PropertyType
    from .search_contractorsop import (
        SearchContractorsRequest,
        SearchContractorsRequestTypedDict,
    )
    from .search_permitsop import SearchPermitsRequest, SearchPermitsRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .validationerror import (
        Context,
        ContextTypedDict,
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .webhookcreate import WebhookCreate, WebhookCreateTypedDict

__all__ = [
    "Context",
    "ContextTypedDict",
    "ContractorProfile",
    "ContractorProfileTypedDict",
    "ContractorSearchResponse",
    "ContractorSearchResponseTypedDict",
    "ContractorSummary",
    "ContractorSummaryTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "ExportPermitsCsvRequest",
    "ExportPermitsCsvRequestTypedDict",
    "GetContractorPermitsRequest",
    "GetContractorPermitsRequestTypedDict",
    "GetContractorRequest",
    "GetContractorRequestTypedDict",
    "GetPermitRequest",
    "GetPermitRequestTypedDict",
    "GetPermitsByAddressRequest",
    "GetPermitsByAddressRequestTypedDict",
    "GetPropertyHistoryRequest",
    "GetPropertyHistoryRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "PermitCategory",
    "PermitDetail",
    "PermitDetailTypedDict",
    "PermitSearchResponse",
    "PermitSearchResponseTypedDict",
    "PermitStatus",
    "PermitSummary",
    "PermitSummaryTypedDict",
    "PropertyType",
    "SearchContractorsRequest",
    "SearchContractorsRequestTypedDict",
    "SearchPermitsRequest",
    "SearchPermitsRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WebhookCreate",
    "WebhookCreateTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "ContractorProfile": ".contractorprofile",
    "ContractorProfileTypedDict": ".contractorprofile",
    "ContractorSearchResponse": ".contractorsearchresponse",
    "ContractorSearchResponseTypedDict": ".contractorsearchresponse",
    "ContractorSummary": ".contractorsummary",
    "ContractorSummaryTypedDict": ".contractorsummary",
    "DeleteWebhookRequest": ".delete_webhookop",
    "DeleteWebhookRequestTypedDict": ".delete_webhookop",
    "ExportPermitsCsvRequest": ".export_permits_csvop",
    "ExportPermitsCsvRequestTypedDict": ".export_permits_csvop",
    "GetContractorPermitsRequest": ".get_contractor_permitsop",
    "GetContractorPermitsRequestTypedDict": ".get_contractor_permitsop",
    "GetContractorRequest": ".get_contractorop",
    "GetContractorRequestTypedDict": ".get_contractorop",
    "GetPermitRequest": ".get_permitop",
    "GetPermitRequestTypedDict": ".get_permitop",
    "GetPermitsByAddressRequest": ".get_permits_by_addressop",
    "GetPermitsByAddressRequestTypedDict": ".get_permits_by_addressop",
    "GetPropertyHistoryRequest": ".get_property_historyop",
    "GetPropertyHistoryRequestTypedDict": ".get_property_historyop",
    "PermitCategory": ".permitcategory",
    "PermitDetail": ".permitdetail",
    "PermitDetailTypedDict": ".permitdetail",
    "PermitSearchResponse": ".permitsearchresponse",
    "PermitSearchResponseTypedDict": ".permitsearchresponse",
    "PermitStatus": ".permitstatus",
    "PermitSummary": ".permitsummary",
    "PermitSummaryTypedDict": ".permitsummary",
    "PropertyType": ".propertytype",
    "SearchContractorsRequest": ".search_contractorsop",
    "SearchContractorsRequestTypedDict": ".search_contractorsop",
    "SearchPermitsRequest": ".search_permitsop",
    "SearchPermitsRequestTypedDict": ".search_permitsop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Context": ".validationerror",
    "ContextTypedDict": ".validationerror",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WebhookCreate": ".webhookcreate",
    "WebhookCreateTypedDict": ".webhookcreate",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
