"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from permitstack.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .battery_retrofit_candidatesop import (
        BatteryRetrofitCandidatesRequest,
        BatteryRetrofitCandidatesRequestTypedDict,
    )
    from .contractorprofile import ContractorProfile, ContractorProfileTypedDict
    from .contractorsearchresponse import (
        ContractorSearchResponse,
        ContractorSearchResponseTypedDict,
    )
    from .contractorsummary import ContractorSummary, ContractorSummaryTypedDict
    from .coverageconfidence import CoverageConfidence, CoverageConfidenceTypedDict
    from .delete_webhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .export_permitsop import ExportPermitsRequest, ExportPermitsRequestTypedDict
    from .get_contractor_permitsop import (
        GetContractorPermitsRequest,
        GetContractorPermitsRequestTypedDict,
    )
    from .get_contractorop import GetContractorRequest, GetContractorRequestTypedDict
    from .get_permitop import GetPermitRequest, GetPermitRequestTypedDict
    from .get_permits_by_addressop import (
        GetPermitsByAddressRequest,
        GetPermitsByAddressRequestTypedDict,
    )
    from .get_property_by_parcelop import (
        GetPropertyByParcelRequest,
        GetPropertyByParcelRequestTypedDict,
    )
    from .get_property_historyop import (
        GetPropertyHistoryRequest,
        GetPropertyHistoryRequestTypedDict,
    )
    from .get_webhook_secretop import (
        GetWebhookSecretRequest,
        GetWebhookSecretRequestTypedDict,
    )
    from .list_permit_eventsop import (
        ListPermitEventsRequest,
        ListPermitEventsRequestTypedDict,
    )
    from .orphan_recoveryop import OrphanRecoveryRequest, OrphanRecoveryRequestTypedDict
    from .permitdetail import PermitDetail, PermitDetailTypedDict
    from .permitenrichment import PermitEnrichment, PermitEnrichmentTypedDict
    from .permiteventout import PermitEventOut, PermitEventOutTypedDict
    from .permiteventsresponse import (
        PermitEventsResponse,
        PermitEventsResponseTypedDict,
    )
    from .permitsearchresponse import (
        PermitSearchResponse,
        PermitSearchResponseTypedDict,
    )
    from .permitstatus import PermitStatus
    from .permitsummary import PermitSummary, PermitSummaryTypedDict
    from .propertyhistoryresponse import (
        PropertyHistoryResponse,
        PropertyHistoryResponseTypedDict,
    )
    from .propertyquery import PropertyQuery, PropertyQueryTypedDict
    from .propertysignals import PropertySignals, PropertySignalsTypedDict
    from .propertysummary import PropertySummary, PropertySummaryTypedDict
    from .propertytype import PropertyType
    from .search_contractorsop import (
        SearchContractorsRequest,
        SearchContractorsRequestTypedDict,
    )
    from .search_permitsop import SearchPermitsRequest, SearchPermitsRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .test_webhookop import TestWebhookRequest, TestWebhookRequestTypedDict
    from .validationerror import (
        Context,
        ContextTypedDict,
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .webhookcreate import WebhookCreate, WebhookCreateTypedDict

__all__ = [
    "BatteryRetrofitCandidatesRequest",
    "BatteryRetrofitCandidatesRequestTypedDict",
    "Context",
    "ContextTypedDict",
    "ContractorProfile",
    "ContractorProfileTypedDict",
    "ContractorSearchResponse",
    "ContractorSearchResponseTypedDict",
    "ContractorSummary",
    "ContractorSummaryTypedDict",
    "CoverageConfidence",
    "CoverageConfidenceTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "ExportPermitsRequest",
    "ExportPermitsRequestTypedDict",
    "GetContractorPermitsRequest",
    "GetContractorPermitsRequestTypedDict",
    "GetContractorRequest",
    "GetContractorRequestTypedDict",
    "GetPermitRequest",
    "GetPermitRequestTypedDict",
    "GetPermitsByAddressRequest",
    "GetPermitsByAddressRequestTypedDict",
    "GetPropertyByParcelRequest",
    "GetPropertyByParcelRequestTypedDict",
    "GetPropertyHistoryRequest",
    "GetPropertyHistoryRequestTypedDict",
    "GetWebhookSecretRequest",
    "GetWebhookSecretRequestTypedDict",
    "ListPermitEventsRequest",
    "ListPermitEventsRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "OrphanRecoveryRequest",
    "OrphanRecoveryRequestTypedDict",
    "PermitDetail",
    "PermitDetailTypedDict",
    "PermitEnrichment",
    "PermitEnrichmentTypedDict",
    "PermitEventOut",
    "PermitEventOutTypedDict",
    "PermitEventsResponse",
    "PermitEventsResponseTypedDict",
    "PermitSearchResponse",
    "PermitSearchResponseTypedDict",
    "PermitStatus",
    "PermitSummary",
    "PermitSummaryTypedDict",
    "PropertyHistoryResponse",
    "PropertyHistoryResponseTypedDict",
    "PropertyQuery",
    "PropertyQueryTypedDict",
    "PropertySignals",
    "PropertySignalsTypedDict",
    "PropertySummary",
    "PropertySummaryTypedDict",
    "PropertyType",
    "SearchContractorsRequest",
    "SearchContractorsRequestTypedDict",
    "SearchPermitsRequest",
    "SearchPermitsRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "TestWebhookRequest",
    "TestWebhookRequestTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WebhookCreate",
    "WebhookCreateTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BatteryRetrofitCandidatesRequest": ".battery_retrofit_candidatesop",
    "BatteryRetrofitCandidatesRequestTypedDict": ".battery_retrofit_candidatesop",
    "ContractorProfile": ".contractorprofile",
    "ContractorProfileTypedDict": ".contractorprofile",
    "ContractorSearchResponse": ".contractorsearchresponse",
    "ContractorSearchResponseTypedDict": ".contractorsearchresponse",
    "ContractorSummary": ".contractorsummary",
    "ContractorSummaryTypedDict": ".contractorsummary",
    "CoverageConfidence": ".coverageconfidence",
    "CoverageConfidenceTypedDict": ".coverageconfidence",
    "DeleteWebhookRequest": ".delete_webhookop",
    "DeleteWebhookRequestTypedDict": ".delete_webhookop",
    "ExportPermitsRequest": ".export_permitsop",
    "ExportPermitsRequestTypedDict": ".export_permitsop",
    "GetContractorPermitsRequest": ".get_contractor_permitsop",
    "GetContractorPermitsRequestTypedDict": ".get_contractor_permitsop",
    "GetContractorRequest": ".get_contractorop",
    "GetContractorRequestTypedDict": ".get_contractorop",
    "GetPermitRequest": ".get_permitop",
    "GetPermitRequestTypedDict": ".get_permitop",
    "GetPermitsByAddressRequest": ".get_permits_by_addressop",
    "GetPermitsByAddressRequestTypedDict": ".get_permits_by_addressop",
    "GetPropertyByParcelRequest": ".get_property_by_parcelop",
    "GetPropertyByParcelRequestTypedDict": ".get_property_by_parcelop",
    "GetPropertyHistoryRequest": ".get_property_historyop",
    "GetPropertyHistoryRequestTypedDict": ".get_property_historyop",
    "GetWebhookSecretRequest": ".get_webhook_secretop",
    "GetWebhookSecretRequestTypedDict": ".get_webhook_secretop",
    "ListPermitEventsRequest": ".list_permit_eventsop",
    "ListPermitEventsRequestTypedDict": ".list_permit_eventsop",
    "OrphanRecoveryRequest": ".orphan_recoveryop",
    "OrphanRecoveryRequestTypedDict": ".orphan_recoveryop",
    "PermitDetail": ".permitdetail",
    "PermitDetailTypedDict": ".permitdetail",
    "PermitEnrichment": ".permitenrichment",
    "PermitEnrichmentTypedDict": ".permitenrichment",
    "PermitEventOut": ".permiteventout",
    "PermitEventOutTypedDict": ".permiteventout",
    "PermitEventsResponse": ".permiteventsresponse",
    "PermitEventsResponseTypedDict": ".permiteventsresponse",
    "PermitSearchResponse": ".permitsearchresponse",
    "PermitSearchResponseTypedDict": ".permitsearchresponse",
    "PermitStatus": ".permitstatus",
    "PermitSummary": ".permitsummary",
    "PermitSummaryTypedDict": ".permitsummary",
    "PropertyHistoryResponse": ".propertyhistoryresponse",
    "PropertyHistoryResponseTypedDict": ".propertyhistoryresponse",
    "PropertyQuery": ".propertyquery",
    "PropertyQueryTypedDict": ".propertyquery",
    "PropertySignals": ".propertysignals",
    "PropertySignalsTypedDict": ".propertysignals",
    "PropertySummary": ".propertysummary",
    "PropertySummaryTypedDict": ".propertysummary",
    "PropertyType": ".propertytype",
    "SearchContractorsRequest": ".search_contractorsop",
    "SearchContractorsRequestTypedDict": ".search_contractorsop",
    "SearchPermitsRequest": ".search_permitsop",
    "SearchPermitsRequestTypedDict": ".search_permitsop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TestWebhookRequest": ".test_webhookop",
    "TestWebhookRequestTypedDict": ".test_webhookop",
    "Context": ".validationerror",
    "ContextTypedDict": ".validationerror",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WebhookCreate": ".webhookcreate",
    "WebhookCreateTypedDict": ".webhookcreate",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
