"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from permitstack.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .battery_retrofit_candidatesop import (
        BatteryRetrofitCandidatesRequest,
        BatteryRetrofitCandidatesRequestTypedDict,
    )
    from .contractorprofile import ContractorProfile, ContractorProfileTypedDict
    from .contractorsearchresponse import (
        ContractorSearchResponse,
        ContractorSearchResponseTypedDict,
    )
    from .contractorsummary import ContractorSummary, ContractorSummaryTypedDict
    from .coverageconfidence import CoverageConfidence, CoverageConfidenceTypedDict
    from .delete_webhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .export_permitsop import ExportPermitsRequest, ExportPermitsRequestTypedDict
    from .featurelocked_error import Detail, DetailTypedDict, Error
    from .get_contractor_permitsop import (
        GetContractorPermitsRequest,
        GetContractorPermitsRequestTypedDict,
    )
    from .get_contractorop import GetContractorRequest, GetContractorRequestTypedDict
    from .get_permitop import GetPermitRequest, GetPermitRequestTypedDict
    from .get_permits_by_addressop import (
        GetPermitsByAddressRequest,
        GetPermitsByAddressRequestTypedDict,
    )
    from .get_property_by_parcelop import (
        GetPropertyByParcelRequest,
        GetPropertyByParcelRequestTypedDict,
    )
    from .get_property_historyop import (
        GetPropertyHistoryRequest,
        GetPropertyHistoryRequestTypedDict,
    )
    from .get_webhook_deliveriesop import (
        GetWebhookDeliveriesRequest,
        GetWebhookDeliveriesRequestTypedDict,
    )
    from .get_webhook_secretop import (
        GetWebhookSecretRequest,
        GetWebhookSecretRequestTypedDict,
    )
    from .hint import Hint, HintTypedDict
    from .jurisdictioncoverage import (
        JurisdictionCoverage,
        JurisdictionCoverageTypedDict,
    )
    from .list_permit_eventsop import (
        ListPermitEventsRequest,
        ListPermitEventsRequestTypedDict,
    )
    from .metrics_citiesop import MetricsCitiesRequest, MetricsCitiesRequestTypedDict
    from .metrics_currentop import MetricsCurrentRequest, MetricsCurrentRequestTypedDict
    from .metrics_monthlyop import MetricsMonthlyRequest, MetricsMonthlyRequestTypedDict
    from .orphan_recoveryop import OrphanRecoveryRequest, OrphanRecoveryRequestTypedDict
    from .permitdetail import (
        PermitDetail,
        PermitDetailCategory,
        PermitDetailStatus,
        PermitDetailTypedDict,
    )
    from .permitenrichment import PermitEnrichment, PermitEnrichmentTypedDict
    from .permiteventout import PermitEventOut, PermitEventOutTypedDict
    from .permiteventsresponse import (
        PermitEventsResponse,
        PermitEventsResponseTypedDict,
    )
    from .permitsearchresponse import (
        PermitSearchResponse,
        PermitSearchResponseTypedDict,
    )
    from .permitstatus import PermitStatus
    from .permitsummary import (
        PermitSummary,
        PermitSummaryCategory,
        PermitSummaryStatus,
        PermitSummaryTypedDict,
    )
    from .propertyhistoryresponse import (
        PropertyHistoryResponse,
        PropertyHistoryResponseTypedDict,
    )
    from .propertyquery import PropertyQuery, PropertyQueryTypedDict
    from .propertysignals import PropertySignals, PropertySignalsTypedDict
    from .propertysummary import PropertySummary, PropertySummaryTypedDict
    from .propertytype import PropertyType
    from .reroof_dueop import ReroofDueRequest, ReroofDueRequestTypedDict
    from .rotate_webhook_secretop import (
        RotateWebhookSecretRequest,
        RotateWebhookSecretRequestTypedDict,
    )
    from .search_contractorsop import (
        SearchContractorsRequest,
        SearchContractorsRequestTypedDict,
    )
    from .search_permitsop import SearchPermitsRequest, SearchPermitsRequestTypedDict
    from .security import Security, SecurityTypedDict
    from .sync_permitsop import SyncPermitsRequest, SyncPermitsRequestTypedDict
    from .system_ageop import SystemAgeRequest, SystemAgeRequestTypedDict
    from .test_webhookop import TestWebhookRequest, TestWebhookRequestTypedDict
    from .update_webhookop import UpdateWebhookRequest, UpdateWebhookRequestTypedDict
    from .validationerror import (
        Context,
        ContextTypedDict,
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .webhookcreate import WebhookCreate, WebhookCreateTypedDict

__all__ = [
    "BatteryRetrofitCandidatesRequest",
    "BatteryRetrofitCandidatesRequestTypedDict",
    "Context",
    "ContextTypedDict",
    "ContractorProfile",
    "ContractorProfileTypedDict",
    "ContractorSearchResponse",
    "ContractorSearchResponseTypedDict",
    "ContractorSummary",
    "ContractorSummaryTypedDict",
    "CoverageConfidence",
    "CoverageConfidenceTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "Detail",
    "DetailTypedDict",
    "Error",
    "ExportPermitsRequest",
    "ExportPermitsRequestTypedDict",
    "GetContractorPermitsRequest",
    "GetContractorPermitsRequestTypedDict",
    "GetContractorRequest",
    "GetContractorRequestTypedDict",
    "GetPermitRequest",
    "GetPermitRequestTypedDict",
    "GetPermitsByAddressRequest",
    "GetPermitsByAddressRequestTypedDict",
    "GetPropertyByParcelRequest",
    "GetPropertyByParcelRequestTypedDict",
    "GetPropertyHistoryRequest",
    "GetPropertyHistoryRequestTypedDict",
    "GetWebhookDeliveriesRequest",
    "GetWebhookDeliveriesRequestTypedDict",
    "GetWebhookSecretRequest",
    "GetWebhookSecretRequestTypedDict",
    "Hint",
    "HintTypedDict",
    "JurisdictionCoverage",
    "JurisdictionCoverageTypedDict",
    "ListPermitEventsRequest",
    "ListPermitEventsRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "MetricsCitiesRequest",
    "MetricsCitiesRequestTypedDict",
    "MetricsCurrentRequest",
    "MetricsCurrentRequestTypedDict",
    "MetricsMonthlyRequest",
    "MetricsMonthlyRequestTypedDict",
    "OrphanRecoveryRequest",
    "OrphanRecoveryRequestTypedDict",
    "PermitDetail",
    "PermitDetailCategory",
    "PermitDetailStatus",
    "PermitDetailTypedDict",
    "PermitEnrichment",
    "PermitEnrichmentTypedDict",
    "PermitEventOut",
    "PermitEventOutTypedDict",
    "PermitEventsResponse",
    "PermitEventsResponseTypedDict",
    "PermitSearchResponse",
    "PermitSearchResponseTypedDict",
    "PermitStatus",
    "PermitSummary",
    "PermitSummaryCategory",
    "PermitSummaryStatus",
    "PermitSummaryTypedDict",
    "PropertyHistoryResponse",
    "PropertyHistoryResponseTypedDict",
    "PropertyQuery",
    "PropertyQueryTypedDict",
    "PropertySignals",
    "PropertySignalsTypedDict",
    "PropertySummary",
    "PropertySummaryTypedDict",
    "PropertyType",
    "ReroofDueRequest",
    "ReroofDueRequestTypedDict",
    "RotateWebhookSecretRequest",
    "RotateWebhookSecretRequestTypedDict",
    "SearchContractorsRequest",
    "SearchContractorsRequestTypedDict",
    "SearchPermitsRequest",
    "SearchPermitsRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "SyncPermitsRequest",
    "SyncPermitsRequestTypedDict",
    "SystemAgeRequest",
    "SystemAgeRequestTypedDict",
    "TestWebhookRequest",
    "TestWebhookRequestTypedDict",
    "UpdateWebhookRequest",
    "UpdateWebhookRequestTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "WebhookCreate",
    "WebhookCreateTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BatteryRetrofitCandidatesRequest": ".battery_retrofit_candidatesop",
    "BatteryRetrofitCandidatesRequestTypedDict": ".battery_retrofit_candidatesop",
    "ContractorProfile": ".contractorprofile",
    "ContractorProfileTypedDict": ".contractorprofile",
    "ContractorSearchResponse": ".contractorsearchresponse",
    "ContractorSearchResponseTypedDict": ".contractorsearchresponse",
    "ContractorSummary": ".contractorsummary",
    "ContractorSummaryTypedDict": ".contractorsummary",
    "CoverageConfidence": ".coverageconfidence",
    "CoverageConfidenceTypedDict": ".coverageconfidence",
    "DeleteWebhookRequest": ".delete_webhookop",
    "DeleteWebhookRequestTypedDict": ".delete_webhookop",
    "ExportPermitsRequest": ".export_permitsop",
    "ExportPermitsRequestTypedDict": ".export_permitsop",
    "Detail": ".featurelocked_error",
    "DetailTypedDict": ".featurelocked_error",
    "Error": ".featurelocked_error",
    "GetContractorPermitsRequest": ".get_contractor_permitsop",
    "GetContractorPermitsRequestTypedDict": ".get_contractor_permitsop",
    "GetContractorRequest": ".get_contractorop",
    "GetContractorRequestTypedDict": ".get_contractorop",
    "GetPermitRequest": ".get_permitop",
    "GetPermitRequestTypedDict": ".get_permitop",
    "GetPermitsByAddressRequest": ".get_permits_by_addressop",
    "GetPermitsByAddressRequestTypedDict": ".get_permits_by_addressop",
    "GetPropertyByParcelRequest": ".get_property_by_parcelop",
    "GetPropertyByParcelRequestTypedDict": ".get_property_by_parcelop",
    "GetPropertyHistoryRequest": ".get_property_historyop",
    "GetPropertyHistoryRequestTypedDict": ".get_property_historyop",
    "GetWebhookDeliveriesRequest": ".get_webhook_deliveriesop",
    "GetWebhookDeliveriesRequestTypedDict": ".get_webhook_deliveriesop",
    "GetWebhookSecretRequest": ".get_webhook_secretop",
    "GetWebhookSecretRequestTypedDict": ".get_webhook_secretop",
    "Hint": ".hint",
    "HintTypedDict": ".hint",
    "JurisdictionCoverage": ".jurisdictioncoverage",
    "JurisdictionCoverageTypedDict": ".jurisdictioncoverage",
    "ListPermitEventsRequest": ".list_permit_eventsop",
    "ListPermitEventsRequestTypedDict": ".list_permit_eventsop",
    "MetricsCitiesRequest": ".metrics_citiesop",
    "MetricsCitiesRequestTypedDict": ".metrics_citiesop",
    "MetricsCurrentRequest": ".metrics_currentop",
    "MetricsCurrentRequestTypedDict": ".metrics_currentop",
    "MetricsMonthlyRequest": ".metrics_monthlyop",
    "MetricsMonthlyRequestTypedDict": ".metrics_monthlyop",
    "OrphanRecoveryRequest": ".orphan_recoveryop",
    "OrphanRecoveryRequestTypedDict": ".orphan_recoveryop",
    "PermitDetail": ".permitdetail",
    "PermitDetailCategory": ".permitdetail",
    "PermitDetailStatus": ".permitdetail",
    "PermitDetailTypedDict": ".permitdetail",
    "PermitEnrichment": ".permitenrichment",
    "PermitEnrichmentTypedDict": ".permitenrichment",
    "PermitEventOut": ".permiteventout",
    "PermitEventOutTypedDict": ".permiteventout",
    "PermitEventsResponse": ".permiteventsresponse",
    "PermitEventsResponseTypedDict": ".permiteventsresponse",
    "PermitSearchResponse": ".permitsearchresponse",
    "PermitSearchResponseTypedDict": ".permitsearchresponse",
    "PermitStatus": ".permitstatus",
    "PermitSummary": ".permitsummary",
    "PermitSummaryCategory": ".permitsummary",
    "PermitSummaryStatus": ".permitsummary",
    "PermitSummaryTypedDict": ".permitsummary",
    "PropertyHistoryResponse": ".propertyhistoryresponse",
    "PropertyHistoryResponseTypedDict": ".propertyhistoryresponse",
    "PropertyQuery": ".propertyquery",
    "PropertyQueryTypedDict": ".propertyquery",
    "PropertySignals": ".propertysignals",
    "PropertySignalsTypedDict": ".propertysignals",
    "PropertySummary": ".propertysummary",
    "PropertySummaryTypedDict": ".propertysummary",
    "PropertyType": ".propertytype",
    "ReroofDueRequest": ".reroof_dueop",
    "ReroofDueRequestTypedDict": ".reroof_dueop",
    "RotateWebhookSecretRequest": ".rotate_webhook_secretop",
    "RotateWebhookSecretRequestTypedDict": ".rotate_webhook_secretop",
    "SearchContractorsRequest": ".search_contractorsop",
    "SearchContractorsRequestTypedDict": ".search_contractorsop",
    "SearchPermitsRequest": ".search_permitsop",
    "SearchPermitsRequestTypedDict": ".search_permitsop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SyncPermitsRequest": ".sync_permitsop",
    "SyncPermitsRequestTypedDict": ".sync_permitsop",
    "SystemAgeRequest": ".system_ageop",
    "SystemAgeRequestTypedDict": ".system_ageop",
    "TestWebhookRequest": ".test_webhookop",
    "TestWebhookRequestTypedDict": ".test_webhookop",
    "UpdateWebhookRequest": ".update_webhookop",
    "UpdateWebhookRequestTypedDict": ".update_webhookop",
    "Context": ".validationerror",
    "ContextTypedDict": ".validationerror",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "WebhookCreate": ".webhookcreate",
    "WebhookCreateTypedDict": ".webhookcreate",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
