"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ContractorProfileTypedDict(TypedDict):
    id: str
    name: str
    license_number: Nullable[str]
    license_state: Nullable[str]
    city: Nullable[str]
    state: Nullable[str]
    total_permits: int
    first_permit_date: Nullable[date]
    last_permit_date: Nullable[date]
    specialties: Nullable[List[str]]
    phone: Nullable[str]
    email: Nullable[str]
    address: Nullable[str]
    zip_code: Nullable[str]
    recent_categories: NotRequired[Nullable[List[str]]]
    avg_project_value: NotRequired[Nullable[float]]


class ContractorProfile(BaseModel):
    id: str

    name: str

    license_number: Nullable[str]

    license_state: Nullable[str]

    city: Nullable[str]

    state: Nullable[str]

    total_permits: int

    first_permit_date: Nullable[date]

    last_permit_date: Nullable[date]

    specialties: Nullable[List[str]]

    phone: Nullable[str]

    email: Nullable[str]

    address: Nullable[str]

    zip_code: Nullable[str]

    recent_categories: OptionalNullable[List[str]] = UNSET

    avg_project_value: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["recent_categories", "avg_project_value"])
        nullable_fields = set(
            [
                "license_number",
                "license_state",
                "city",
                "state",
                "first_permit_date",
                "last_permit_date",
                "specialties",
                "phone",
                "email",
                "address",
                "zip_code",
                "recent_categories",
                "avg_project_value",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
