"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contractorsummary import ContractorSummary, ContractorSummaryTypedDict
from permitstack.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ContractorSearchResponseTypedDict(TypedDict):
    total: int
    page: int
    per_page: int
    results: List[ContractorSummaryTypedDict]


class ContractorSearchResponse(BaseModel):
    total: int

    page: int

    per_page: int

    results: List[ContractorSummary]
