"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


Error = Literal["feature_locked",]


class DetailTypedDict(TypedDict):
    error: NotRequired[Error]
    feature: NotRequired[str]
    message: NotRequired[str]
    upgrade_url: NotRequired[str]
    current_tier: NotRequired[str]


class Detail(BaseModel):
    error: Optional[Error] = None

    feature: Optional[str] = None

    message: Optional[str] = None

    upgrade_url: Optional[str] = None

    current_tier: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["error", "feature", "message", "upgrade_url", "current_tier"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
