"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import BaseModel
from permitstack.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPermitRequestTypedDict(TypedDict):
    permit_id: str


class GetPermitRequest(BaseModel):
    permit_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
