"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from permitstack.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPropertyHistoryRequestTypedDict(TypedDict):
    address: str
    r"""Street address to look up (e.g. '123 Main St')"""
    city: NotRequired[Nullable[str]]
    r"""Optional city to disambiguate identical street addresses"""
    state: NotRequired[Nullable[str]]
    r"""Optional 2-letter state code"""
    zip: NotRequired[Nullable[str]]
    r"""Optional ZIP (prefix-matched)"""
    page: NotRequired[int]
    per_page: NotRequired[int]
    limit: NotRequired[Nullable[int]]
    r"""Alias of per_page."""


class GetPropertyHistoryRequest(BaseModel):
    address: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Street address to look up (e.g. '123 Main St')"""

    city: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Optional city to disambiguate identical street addresses"""

    state: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Optional 2-letter state code"""

    zip: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Optional ZIP (prefix-matched)"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    per_page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    limit: Annotated[
        OptionalNullable[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of per_page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["city", "state", "zip", "page", "per_page", "limit"])
        nullable_fields = set(["city", "state", "zip", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
