"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import BaseModel
from permitstack.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class GetPropertyHistoryRequestTypedDict(TypedDict):
    address: str
    r"""Street address to look up"""


class GetPropertyHistoryRequest(BaseModel):
    address: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Street address to look up"""
