"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from permitstack.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetPropertyByParcelRequestTypedDict(TypedDict):
    parcel: str
    r"""Parcel number / APN / folio. Formatting is ignored — dashes, dots and spaces are stripped before matching."""
    state: NotRequired[Nullable[str]]
    r"""Optional 2-letter state to disambiguate the same parcel number across counties"""
    page: NotRequired[int]
    per_page: NotRequired[int]


class GetPropertyByParcelRequest(BaseModel):
    parcel: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Parcel number / APN / folio. Formatting is ignored — dashes, dots and spaces are stripped before matching."""

    state: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Optional 2-letter state to disambiguate the same parcel number across counties"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    per_page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["state", "page", "per_page"])
        nullable_fields = set(["state"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
