"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class JurisdictionCoverageTypedDict(TypedDict):
    r"""How current one jurisdiction's data is, for the jurisdictions on THIS page of results.

    Lets you tell \"this source has not yet published the window you asked about\" apart from
    \"this data is missing\": `data_through` is the newest permit we hold for the jurisdiction,
    and `with_contractor` shows how many rows on this page carry a contractor name.
    """

    jurisdiction: str
    data_through: NotRequired[Nullable[str]]
    status: NotRequired[str]
    results_on_page: NotRequired[int]
    with_contractor: NotRequired[int]


class JurisdictionCoverage(BaseModel):
    r"""How current one jurisdiction's data is, for the jurisdictions on THIS page of results.

    Lets you tell \"this source has not yet published the window you asked about\" apart from
    \"this data is missing\": `data_through` is the newest permit we hold for the jurisdiction,
    and `with_contractor` shows how many rows on this page carry a contractor name.
    """

    jurisdiction: str

    data_through: OptionalNullable[str] = UNSET

    status: Optional[str] = "not_measured"

    results_on_page: Optional[int] = 0

    with_contractor: Optional[int] = 0

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["data_through", "status", "results_on_page", "with_contractor"]
        )
        nullable_fields = set(["data_through"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
