"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from permitstack.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrphanRecoveryRequestTypedDict(TypedDict):
    installer: str
    r"""Installer name to match (contractor/applicant/owner)"""
    state: NotRequired[Nullable[str]]
    r"""2-letter state code"""
    city: NotRequired[Nullable[str]]
    r"""City name"""
    zip_code: NotRequired[Nullable[str]]
    r"""5-digit ZIP"""
    jurisdiction: NotRequired[Nullable[str]]
    r"""Jurisdiction name (partial)"""
    page: NotRequired[int]
    per_page: NotRequired[int]


class OrphanRecoveryRequest(BaseModel):
    installer: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Installer name to match (contractor/applicant/owner)"""

    state: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""2-letter state code"""

    city: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""City name"""

    zip_code: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""5-digit ZIP"""

    jurisdiction: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Jurisdiction name (partial)"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    per_page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 25

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["state", "city", "zip_code", "jurisdiction", "page", "per_page"]
        )
        nullable_fields = set(["state", "city", "zip_code", "jurisdiction"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
