"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permitenrichment import PermitEnrichment, PermitEnrichmentTypedDict
from datetime import date
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PermitDetailTypedDict(TypedDict):
    id: str
    permit_number: Nullable[str]
    status: str
    category: str
    tags: Nullable[List[str]]
    property_type: str
    address_street: Nullable[str]
    address_city: Nullable[str]
    address_state: Nullable[str]
    address_zip: Nullable[str]
    description_raw: Nullable[str]
    estimated_value: Nullable[float]
    date_filed: Nullable[date]
    date_issued: Nullable[date]
    date_completed: Nullable[date]
    date_expired: Nullable[date]
    stories: Nullable[int]
    units: Nullable[int]
    square_footage: Nullable[float]
    applicant_name: Nullable[str]
    owner_name: Nullable[str]
    contractor_name: NotRequired[Nullable[str]]
    jurisdiction_name: NotRequired[Nullable[str]]
    latitude: NotRequired[Nullable[float]]
    longitude: NotRequired[Nullable[float]]
    enrichment: NotRequired[Nullable[PermitEnrichmentTypedDict]]
    record_kind: NotRequired[str]
    fee_amount: NotRequired[Nullable[float]]
    r"""Permit/inspection fee. Frequently null — most open-data feeds do not publish fee data."""
    contractor_license: NotRequired[Nullable[str]]
    created_at: NotRequired[Nullable[str]]


class PermitDetail(BaseModel):
    id: str

    permit_number: Nullable[str]

    status: str

    category: str

    tags: Nullable[List[str]]

    property_type: str

    address_street: Nullable[str]

    address_city: Nullable[str]

    address_state: Nullable[str]

    address_zip: Nullable[str]

    description_raw: Nullable[str]

    estimated_value: Nullable[float]

    date_filed: Nullable[date]

    date_issued: Nullable[date]

    date_completed: Nullable[date]

    date_expired: Nullable[date]

    stories: Nullable[int]

    units: Nullable[int]

    square_footage: Nullable[float]

    applicant_name: Nullable[str]

    owner_name: Nullable[str]

    contractor_name: OptionalNullable[str] = UNSET

    jurisdiction_name: OptionalNullable[str] = UNSET

    latitude: OptionalNullable[float] = UNSET

    longitude: OptionalNullable[float] = UNSET

    enrichment: OptionalNullable[PermitEnrichment] = UNSET

    record_kind: Optional[str] = "permit"

    fee_amount: OptionalNullable[float] = UNSET
    r"""Permit/inspection fee. Frequently null — most open-data feeds do not publish fee data."""

    contractor_license: OptionalNullable[str] = UNSET

    created_at: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "contractor_name",
                "jurisdiction_name",
                "latitude",
                "longitude",
                "enrichment",
                "record_kind",
                "fee_amount",
                "contractor_license",
                "created_at",
            ]
        )
        nullable_fields = set(
            [
                "permit_number",
                "tags",
                "address_street",
                "address_city",
                "address_state",
                "address_zip",
                "description_raw",
                "estimated_value",
                "date_filed",
                "date_issued",
                "date_completed",
                "contractor_name",
                "jurisdiction_name",
                "latitude",
                "longitude",
                "enrichment",
                "date_expired",
                "fee_amount",
                "stories",
                "units",
                "square_footage",
                "applicant_name",
                "owner_name",
                "contractor_license",
                "created_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
