"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permiteventout import PermitEventOut, PermitEventOutTypedDict
from permitstack.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PermitEventsResponseTypedDict(TypedDict):
    total: int
    page: int
    per_page: int
    results: List[PermitEventOutTypedDict]


class PermitEventsResponse(BaseModel):
    total: int

    page: int

    per_page: int

    results: List[PermitEventOut]
