"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


PermitCategory = Literal[
    "new_construction",
    "renovation",
    "demolition",
    "electrical",
    "plumbing",
    "mechanical",
    "roofing",
    "solar",
    "ev_charger",
    "hvac",
    "fire_alarm",
    "sign",
    "fence",
    "pool",
    "foundation",
    "addition",
    "interior_remodel",
    "grading",
    "other",
]
