"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class PermitEventOutTypedDict(TypedDict):
    id: int
    permit_id: str
    event_type: str
    detected_at: datetime
    old_value: NotRequired[Nullable[str]]
    new_value: NotRequired[Nullable[str]]
    occurred_on: NotRequired[Nullable[date]]
    permit_number: NotRequired[Nullable[str]]
    address_street: NotRequired[Nullable[str]]
    address_city: NotRequired[Nullable[str]]
    address_state: NotRequired[Nullable[str]]
    category: NotRequired[Nullable[str]]
    jurisdiction_name: NotRequired[Nullable[str]]
    contractor_id: NotRequired[Nullable[str]]
    r"""Stable id of the contractor of record, joinable to /v1/contractors/{id}. Null where the source publishes no contractor."""
    property_type: NotRequired[Nullable[str]]
    r"""RESIDENTIAL, COMMERCIAL, MIXED_USE, ... or UNKNOWN, as on /v1/permits/search."""
    description: NotRequired[Nullable[str]]
    r"""The permit's scope of work as the jurisdiction published it (description_raw on search)."""


class PermitEventOut(BaseModel):
    id: int

    permit_id: str

    event_type: str

    detected_at: datetime

    old_value: OptionalNullable[str] = UNSET

    new_value: OptionalNullable[str] = UNSET

    occurred_on: OptionalNullable[date] = UNSET

    permit_number: OptionalNullable[str] = UNSET

    address_street: OptionalNullable[str] = UNSET

    address_city: OptionalNullable[str] = UNSET

    address_state: OptionalNullable[str] = UNSET

    category: OptionalNullable[str] = UNSET

    jurisdiction_name: OptionalNullable[str] = UNSET

    contractor_id: OptionalNullable[str] = UNSET
    r"""Stable id of the contractor of record, joinable to /v1/contractors/{id}. Null where the source publishes no contractor."""

    property_type: OptionalNullable[str] = UNSET
    r"""RESIDENTIAL, COMMERCIAL, MIXED_USE, ... or UNKNOWN, as on /v1/permits/search."""

    description: OptionalNullable[str] = UNSET
    r"""The permit's scope of work as the jurisdiction published it (description_raw on search)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "old_value",
                "new_value",
                "occurred_on",
                "permit_number",
                "address_street",
                "address_city",
                "address_state",
                "category",
                "jurisdiction_name",
                "contractor_id",
                "property_type",
                "description",
            ]
        )
        nullable_fields = set(
            [
                "old_value",
                "new_value",
                "occurred_on",
                "permit_number",
                "address_street",
                "address_city",
                "address_state",
                "category",
                "jurisdiction_name",
                "contractor_id",
                "property_type",
                "description",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
