"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permitsummary import PermitSummary, PermitSummaryTypedDict
from permitstack.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PermitSearchResponseTypedDict(TypedDict):
    total: int
    page: int
    per_page: int
    results: List[PermitSummaryTypedDict]


class PermitSearchResponse(BaseModel):
    total: int

    page: int

    per_page: int

    results: List[PermitSummary]
