"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .coverageconfidence import CoverageConfidence, CoverageConfidenceTypedDict
from .hint import Hint, HintTypedDict
from .jurisdictioncoverage import JurisdictionCoverage, JurisdictionCoverageTypedDict
from .permitsummary import PermitSummary, PermitSummaryTypedDict
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PermitSearchResponseTypedDict(TypedDict):
    total: Nullable[int]
    page: int
    per_page: int
    results: List[PermitSummaryTypedDict]
    hints: NotRequired[List[HintTypedDict]]
    coverage_confidence: NotRequired[Nullable[CoverageConfidenceTypedDict]]
    tier_window_days: NotRequired[Nullable[int]]
    tier_window_from: NotRequired[Nullable[str]]
    tier_window_clamped: NotRequired[bool]
    tier_window_upgrade_url: NotRequired[Nullable[str]]
    locked_fields: NotRequired[Nullable[List[str]]]
    locked_upgrade_url: NotRequired[Nullable[str]]
    coverage: NotRequired[List[JurisdictionCoverageTypedDict]]
    total_capped: NotRequired[bool]
    total_unknown: NotRequired[bool]


class PermitSearchResponse(BaseModel):
    total: Nullable[int]

    page: int

    per_page: int

    results: List[PermitSummary]

    hints: Optional[List[Hint]] = None

    coverage_confidence: OptionalNullable[CoverageConfidence] = UNSET

    tier_window_days: OptionalNullable[int] = UNSET

    tier_window_from: OptionalNullable[str] = UNSET

    tier_window_clamped: Optional[bool] = False

    tier_window_upgrade_url: OptionalNullable[str] = UNSET

    locked_fields: OptionalNullable[List[str]] = UNSET

    locked_upgrade_url: OptionalNullable[str] = UNSET

    coverage: Optional[List[JurisdictionCoverage]] = None

    total_capped: Optional[bool] = False

    total_unknown: Optional[bool] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "hints",
                "coverage_confidence",
                "tier_window_days",
                "tier_window_from",
                "tier_window_clamped",
                "tier_window_upgrade_url",
                "locked_fields",
                "locked_upgrade_url",
                "coverage",
                "total_capped",
                "total_unknown",
            ]
        )
        nullable_fields = set(
            [
                "total",
                "coverage_confidence",
                "tier_window_days",
                "tier_window_from",
                "tier_window_upgrade_url",
                "locked_fields",
                "locked_upgrade_url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
