"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


PermitStatus = Literal[
    "filed",
    "issued",
    "in_progress",
    "final",
    "expired",
    "cancelled",
    "revoked",
    "unknown",
]
