"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class PropertyQueryTypedDict(TypedDict):
    address: NotRequired[Nullable[str]]
    parcel: NotRequired[Nullable[str]]
    city: NotRequired[Nullable[str]]
    state: NotRequired[Nullable[str]]
    zip: NotRequired[Nullable[str]]


class PropertyQuery(BaseModel):
    address: OptionalNullable[str] = UNSET

    parcel: OptionalNullable[str] = UNSET

    city: OptionalNullable[str] = UNSET

    state: OptionalNullable[str] = UNSET

    zip: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "parcel", "city", "state", "zip"])
        nullable_fields = set(["address", "parcel", "city", "state", "zip"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
