"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .propertysignals import PropertySignals, PropertySignalsTypedDict
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Dict, List
from typing_extensions import NotRequired, TypedDict


class PropertySummaryTypedDict(TypedDict):
    total_permits: int
    categories: Dict[str, int]
    jurisdictions: List[str]
    contractors: List[str]
    signals: PropertySignalsTypedDict
    r"""Boolean/scalar rollups useful for underwriting, valuation and diligence.

    Derived from permit category + tags + offline enrichment across every
    permit matched at the address. Dates are the most-recent permit of that
    kind (ISO yyyy-mm-dd) so you can reason about roof/solar/pool age.
    """
    first_permit_date: NotRequired[Nullable[str]]
    last_permit_date: NotRequired[Nullable[str]]
    years_of_history: NotRequired[Nullable[int]]
    total_estimated_value: NotRequired[Nullable[float]]


class PropertySummary(BaseModel):
    total_permits: int

    categories: Dict[str, int]

    jurisdictions: List[str]

    contractors: List[str]

    signals: PropertySignals
    r"""Boolean/scalar rollups useful for underwriting, valuation and diligence.

    Derived from permit category + tags + offline enrichment across every
    permit matched at the address. Dates are the most-recent permit of that
    kind (ISO yyyy-mm-dd) so you can reason about roof/solar/pool age.
    """

    first_permit_date: OptionalNullable[str] = UNSET

    last_permit_date: OptionalNullable[str] = UNSET

    years_of_history: OptionalNullable[int] = UNSET

    total_estimated_value: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "first_permit_date",
                "last_permit_date",
                "years_of_history",
                "total_estimated_value",
            ]
        )
        nullable_fields = set(
            [
                "first_permit_date",
                "last_permit_date",
                "years_of_history",
                "total_estimated_value",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
