"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PropertySignalsTypedDict(TypedDict):
    r"""Boolean/scalar rollups useful for underwriting, valuation and diligence.

    Derived from permit category + tags + offline enrichment across every
    permit matched at the address. Dates are the most-recent permit of that
    kind (ISO yyyy-mm-dd) so you can reason about roof/solar/pool age.
    """

    has_solar: NotRequired[bool]
    solar_kw: NotRequired[Nullable[float]]
    last_solar_date: NotRequired[Nullable[str]]
    has_battery: NotRequired[bool]
    last_battery_date: NotRequired[Nullable[str]]
    has_roofing: NotRequired[bool]
    last_roofing_date: NotRequired[Nullable[str]]
    has_pool: NotRequired[bool]
    last_pool_date: NotRequired[Nullable[str]]
    has_addition: NotRequired[bool]
    has_new_construction: NotRequired[bool]
    has_electrical: NotRequired[bool]
    has_hvac: NotRequired[bool]
    last_hvac_date: NotRequired[Nullable[str]]
    has_plumbing: NotRequired[bool]
    has_demolition: NotRequired[bool]
    last_activity_date: NotRequired[Nullable[str]]


class PropertySignals(BaseModel):
    r"""Boolean/scalar rollups useful for underwriting, valuation and diligence.

    Derived from permit category + tags + offline enrichment across every
    permit matched at the address. Dates are the most-recent permit of that
    kind (ISO yyyy-mm-dd) so you can reason about roof/solar/pool age.
    """

    has_solar: Optional[bool] = False

    solar_kw: OptionalNullable[float] = UNSET

    last_solar_date: OptionalNullable[str] = UNSET

    has_battery: Optional[bool] = False

    last_battery_date: OptionalNullable[str] = UNSET

    has_roofing: Optional[bool] = False

    last_roofing_date: OptionalNullable[str] = UNSET

    has_pool: Optional[bool] = False

    last_pool_date: OptionalNullable[str] = UNSET

    has_addition: Optional[bool] = False

    has_new_construction: Optional[bool] = False

    has_electrical: Optional[bool] = False

    has_hvac: Optional[bool] = False

    last_hvac_date: OptionalNullable[str] = UNSET

    has_plumbing: Optional[bool] = False

    has_demolition: Optional[bool] = False

    last_activity_date: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "has_solar",
                "solar_kw",
                "last_solar_date",
                "has_battery",
                "last_battery_date",
                "has_roofing",
                "last_roofing_date",
                "has_pool",
                "last_pool_date",
                "has_addition",
                "has_new_construction",
                "has_electrical",
                "has_hvac",
                "last_hvac_date",
                "has_plumbing",
                "has_demolition",
                "last_activity_date",
            ]
        )
        nullable_fields = set(
            [
                "solar_kw",
                "last_solar_date",
                "last_battery_date",
                "last_roofing_date",
                "last_pool_date",
                "last_hvac_date",
                "last_activity_date",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
