"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .coverageconfidence import CoverageConfidence, CoverageConfidenceTypedDict
from .jurisdictioncoverage import JurisdictionCoverage, JurisdictionCoverageTypedDict
from .permitsummary import PermitSummary, PermitSummaryTypedDict
from .propertyquery import PropertyQuery, PropertyQueryTypedDict
from .propertysummary import PropertySummary, PropertySummaryTypedDict
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class PropertyHistoryResponseTypedDict(TypedDict):
    query: PropertyQueryTypedDict
    found: bool
    total_matches: int
    truncated: bool
    summary: PropertySummaryTypedDict
    page: int
    per_page: int
    has_more: bool
    permits: List[PermitSummaryTypedDict]
    distinct_addresses: NotRequired[Nullable[int]]
    distinct_jurisdictions: NotRequired[Nullable[int]]
    fan_out_warning: NotRequired[Nullable[str]]
    coverage: NotRequired[Nullable[CoverageConfidenceTypedDict]]
    data_currency: NotRequired[Nullable[List[JurisdictionCoverageTypedDict]]]


class PropertyHistoryResponse(BaseModel):
    query: PropertyQuery

    found: bool

    total_matches: int

    truncated: bool

    summary: PropertySummary

    page: int

    per_page: int

    has_more: bool

    permits: List[PermitSummary]

    distinct_addresses: OptionalNullable[int] = UNSET

    distinct_jurisdictions: OptionalNullable[int] = UNSET

    fan_out_warning: OptionalNullable[str] = UNSET

    coverage: OptionalNullable[CoverageConfidence] = UNSET

    data_currency: OptionalNullable[List[JurisdictionCoverage]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "distinct_addresses",
                "distinct_jurisdictions",
                "fan_out_warning",
                "coverage",
                "data_currency",
            ]
        )
        nullable_fields = set(
            [
                "distinct_addresses",
                "distinct_jurisdictions",
                "fan_out_warning",
                "coverage",
                "data_currency",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
