"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import BaseModel
from permitstack.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RotateWebhookSecretRequestTypedDict(TypedDict):
    webhook_id: str


class RotateWebhookSecretRequest(BaseModel):
    webhook_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
