"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permitcategory import PermitCategory
from .permitstatus import PermitStatus
from .propertytype import PropertyType
from datetime import date
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from permitstack.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchPermitsRequestTypedDict(TypedDict):
    zip_code: NotRequired[Nullable[str]]
    r"""5-digit ZIP code"""
    city: NotRequired[Nullable[str]]
    r"""City name"""
    state: NotRequired[Nullable[str]]
    r"""2-letter state code"""
    lat: NotRequired[Nullable[float]]
    r"""Latitude for radius search"""
    lng: NotRequired[Nullable[float]]
    r"""Longitude for radius search"""
    radius_miles: NotRequired[float]
    r"""Radius in miles (used with lat/lng)"""
    category: NotRequired[Nullable[PermitCategory]]
    r"""Permit category (e.g. solar, roofing, hvac)"""
    status: NotRequired[Nullable[PermitStatus]]
    r"""Permit status (e.g. issued, filed, final)"""
    property_type: NotRequired[Nullable[PropertyType]]
    r"""Property type (e.g. residential, commercial)"""
    tag: NotRequired[Nullable[str]]
    r"""Filter by tag"""
    filed_after: NotRequired[Nullable[date]]
    r"""Filed on or after this date"""
    filed_before: NotRequired[Nullable[date]]
    r"""Filed on or before this date"""
    issued_after: NotRequired[Nullable[date]]
    r"""Issued on or after this date"""
    issued_before: NotRequired[Nullable[date]]
    r"""Issued on or before this date"""
    min_value: NotRequired[Nullable[float]]
    r"""Minimum estimated value"""
    max_value: NotRequired[Nullable[float]]
    r"""Maximum estimated value"""
    q: NotRequired[Nullable[str]]
    r"""Full-text search query"""
    contractor_name: NotRequired[Nullable[str]]
    r"""Contractor name (partial match)"""
    page: NotRequired[int]
    per_page: NotRequired[int]


class SearchPermitsRequest(BaseModel):
    zip_code: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""5-digit ZIP code"""

    city: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""City name"""

    state: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""2-letter state code"""

    lat: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Latitude for radius search"""

    lng: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Longitude for radius search"""

    radius_miles: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 5
    r"""Radius in miles (used with lat/lng)"""

    category: Annotated[
        OptionalNullable[PermitCategory],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Permit category (e.g. solar, roofing, hvac)"""

    status: Annotated[
        OptionalNullable[PermitStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Permit status (e.g. issued, filed, final)"""

    property_type: Annotated[
        OptionalNullable[PropertyType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Property type (e.g. residential, commercial)"""

    tag: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter by tag"""

    filed_after: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filed on or after this date"""

    filed_before: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filed on or before this date"""

    issued_after: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Issued on or after this date"""

    issued_before: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Issued on or before this date"""

    min_value: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Minimum estimated value"""

    max_value: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Maximum estimated value"""

    q: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Full-text search query"""

    contractor_name: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Contractor name (partial match)"""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    per_page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 25

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "zip_code",
                "city",
                "state",
                "lat",
                "lng",
                "radius_miles",
                "category",
                "status",
                "property_type",
                "tag",
                "filed_after",
                "filed_before",
                "issued_after",
                "issued_before",
                "min_value",
                "max_value",
                "q",
                "contractor_name",
                "page",
                "per_page",
            ]
        )
        nullable_fields = set(
            [
                "zip_code",
                "city",
                "state",
                "lat",
                "lng",
                "category",
                "status",
                "property_type",
                "tag",
                "filed_after",
                "filed_before",
                "issued_after",
                "issued_before",
                "min_value",
                "max_value",
                "q",
                "contractor_name",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
