"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permitstatus import PermitStatus
from .propertytype import PropertyType
from datetime import date
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from permitstack.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchPermitsRequestTypedDict(TypedDict):
    zip_code: NotRequired[Nullable[str]]
    r"""5-digit ZIP code"""
    city: NotRequired[Nullable[str]]
    r"""City name"""
    state: NotRequired[Nullable[str]]
    r"""2-letter state code"""
    jurisdiction: NotRequired[Nullable[str]]
    r"""Jurisdiction name (e.g. 'Wake County', 'Tacoma') or partial match"""
    address: NotRequired[Nullable[str]]
    r"""Street address, partial + case-insensitive (e.g. '1600 Pennsylvania') — indexed, fast"""
    lat: NotRequired[Nullable[float]]
    r"""Latitude for radius search"""
    lng: NotRequired[Nullable[float]]
    r"""Longitude for radius search"""
    radius_miles: NotRequired[float]
    r"""Radius in miles (used with lat/lng)"""
    fields: NotRequired[str]
    r"""'summary' (default) or 'full'. With 'full' each result is a PermitDetail rather than a PermitSummary -- the same nine extra columns GET /v1/permits/{id} returns (record_kind, date_expired, fee_amount, stories, units, square_footage, applicant_name, contractor_license, created_at) -- so you do not fetch them one permit at a time. See the PermitDetail schema for their types; the declared response schema here is PermitSummary, which is the default shape. Developer plan and above."""
    bbox: NotRequired[Nullable[str]]
    r"""Map-viewport bounding box 'minLng,minLat,maxLng,maxLat'. Returns permits whose location falls inside the box (geocoded permits only)."""
    polygon: NotRequired[Nullable[str]]
    r"""A drawn area as a GeoJSON Polygon geometry (URL-encoded), e.g. {\"type\":\"Polygon\",\"coordinates\":[[[lng,lat],...]]}. Returns permits inside the polygon (geocoded permits only)."""
    category: NotRequired[Nullable[str]]
    r"""Permit category (e.g. solar, SOLAR, roofing, hvac — case insensitive)"""
    status: NotRequired[Nullable[PermitStatus]]
    r"""Permit status (e.g. issued, filed, final)"""
    property_type: NotRequired[Nullable[PropertyType]]
    r"""Property type (e.g. residential, commercial)"""
    tag: NotRequired[Nullable[str]]
    r"""Filter by tag"""
    record_kind: NotRequired[str]
    r"""Record kind: 'permit' (default, building permits only), 'contractor', 'tag', 'non_building', 'admin', or 'all'"""
    filed_after: NotRequired[Nullable[date]]
    r"""Filed on or after this date"""
    filed_before: NotRequired[Nullable[date]]
    r"""Filed on or before this date"""
    issued_after: NotRequired[Nullable[date]]
    r"""Issued on or after this date"""
    issued_before: NotRequired[Nullable[date]]
    r"""Issued on or before this date"""
    date_after: NotRequired[Nullable[date]]
    r"""On or after this date, matched against whichever date a record has (issued, else filed). Use this when a source populates only one of issued/filed — e.g. issued-only feeds vs filed-only feeds."""
    date_before: NotRequired[Nullable[date]]
    r"""On or before this date, matched against whichever date a record has (issued, else filed)."""
    parcel: NotRequired[Nullable[str]]
    r"""Parcel number / APN / folio (formatting ignored). Returns permits on that parcel where the source publishes one."""
    min_value: NotRequired[Nullable[float]]
    r"""Minimum estimated value"""
    max_value: NotRequired[Nullable[float]]
    r"""Maximum estimated value"""
    min_solar_kw: NotRequired[Nullable[float]]
    r"""Minimum extracted solar system size (kW DC)"""
    max_solar_kw: NotRequired[Nullable[float]]
    r"""Maximum extracted solar system size (kW DC)"""
    min_sqft: NotRequired[Nullable[float]]
    r"""Minimum square footage mentioned (from enrichment)"""
    has_enrichment: NotRequired[Nullable[bool]]
    r"""Only permits that have (true) or lack (false) LLM enrichment"""
    scope: NotRequired[Nullable[str]]
    r"""Substring match on the enriched work scope"""
    q: NotRequired[Nullable[str]]
    r"""Case-insensitive substring match across description, address, and permit number. Terms under 3 characters are matched but not counted: `total` is null with total_unknown=true (a 1-2 character term has no trigram index and the count would cost tens of seconds)."""
    contractor_name: NotRequired[Nullable[str]]
    r"""Contractor name (partial match)"""
    owner_filed: NotRequired[Nullable[bool]]
    r"""true = owner-filed permits only (no contractor on record but an owner name is present — often a DIY/homeowner lead, though for feeds that don't capture contractors the owner may be a builder or institution); false = permits that have a contractor"""
    has_owner_address: NotRequired[Nullable[bool]]
    r"""true = only permits that carry a property-owner mailing address; false = only those that do not. Coverage varies sharply by jurisdiction (we hold the county assessor roll for some and not others), so this is a targeting filter rather than a defect: it returns exactly the rows that are actionable. The address itself is visible on Business and above."""
    page: NotRequired[int]
    per_page: NotRequired[int]
    r"""Results per page. Above your plan's maximum this is clamped, not rejected; the response echoes the per_page actually applied."""
    keyword: NotRequired[Nullable[str]]
    r"""Alias of `q`."""
    date_from: NotRequired[Nullable[date]]
    r"""Alias of `date_after`."""
    date_to: NotRequired[Nullable[date]]
    r"""Alias of `date_before`."""
    start_date: NotRequired[Nullable[date]]
    r"""Alias of `date_after`."""
    end_date: NotRequired[Nullable[date]]
    r"""Alias of `date_before`."""
    limit: NotRequired[Nullable[int]]
    r"""Alias of `per_page`. Clamped to your plan's maximum, not rejected."""
    count_only: NotRequired[bool]
    r"""Return only the total for these filters -- no permit records. Skips the row fetch entirely, so it is markedly cheaper for both of us when you are sizing a query rather than reading it. `results` comes back empty and `total_capped` / `total_unknown` mean exactly what they always do."""


class SearchPermitsRequest(BaseModel):
    zip_code: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""5-digit ZIP code"""

    city: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""City name"""

    state: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""2-letter state code"""

    jurisdiction: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Jurisdiction name (e.g. 'Wake County', 'Tacoma') or partial match"""

    address: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Street address, partial + case-insensitive (e.g. '1600 Pennsylvania') — indexed, fast"""

    lat: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Latitude for radius search"""

    lng: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Longitude for radius search"""

    radius_miles: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 5.0
    r"""Radius in miles (used with lat/lng)"""

    fields: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "summary"
    r"""'summary' (default) or 'full'. With 'full' each result is a PermitDetail rather than a PermitSummary -- the same nine extra columns GET /v1/permits/{id} returns (record_kind, date_expired, fee_amount, stories, units, square_footage, applicant_name, contractor_license, created_at) -- so you do not fetch them one permit at a time. See the PermitDetail schema for their types; the declared response schema here is PermitSummary, which is the default shape. Developer plan and above."""

    bbox: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Map-viewport bounding box 'minLng,minLat,maxLng,maxLat'. Returns permits whose location falls inside the box (geocoded permits only)."""

    polygon: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""A drawn area as a GeoJSON Polygon geometry (URL-encoded), e.g. {\"type\":\"Polygon\",\"coordinates\":[[[lng,lat],...]]}. Returns permits inside the polygon (geocoded permits only)."""

    category: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Permit category (e.g. solar, SOLAR, roofing, hvac — case insensitive)"""

    status: Annotated[
        OptionalNullable[PermitStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Permit status (e.g. issued, filed, final)"""

    property_type: Annotated[
        OptionalNullable[PropertyType],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Property type (e.g. residential, commercial)"""

    tag: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter by tag"""

    record_kind: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "permit"
    r"""Record kind: 'permit' (default, building permits only), 'contractor', 'tag', 'non_building', 'admin', or 'all'"""

    filed_after: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filed on or after this date"""

    filed_before: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filed on or before this date"""

    issued_after: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Issued on or after this date"""

    issued_before: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Issued on or before this date"""

    date_after: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""On or after this date, matched against whichever date a record has (issued, else filed). Use this when a source populates only one of issued/filed — e.g. issued-only feeds vs filed-only feeds."""

    date_before: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""On or before this date, matched against whichever date a record has (issued, else filed)."""

    parcel: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Parcel number / APN / folio (formatting ignored). Returns permits on that parcel where the source publishes one."""

    min_value: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Minimum estimated value"""

    max_value: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Maximum estimated value"""

    min_solar_kw: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Minimum extracted solar system size (kW DC)"""

    max_solar_kw: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Maximum extracted solar system size (kW DC)"""

    min_sqft: Annotated[
        OptionalNullable[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Minimum square footage mentioned (from enrichment)"""

    has_enrichment: Annotated[
        OptionalNullable[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Only permits that have (true) or lack (false) LLM enrichment"""

    scope: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Substring match on the enriched work scope"""

    q: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Case-insensitive substring match across description, address, and permit number. Terms under 3 characters are matched but not counted: `total` is null with total_unknown=true (a 1-2 character term has no trigram index and the count would cost tens of seconds)."""

    contractor_name: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Contractor name (partial match)"""

    owner_filed: Annotated[
        OptionalNullable[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""true = owner-filed permits only (no contractor on record but an owner name is present — often a DIY/homeowner lead, though for feeds that don't capture contractors the owner may be a builder or institution); false = permits that have a contractor"""

    has_owner_address: Annotated[
        OptionalNullable[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""true = only permits that carry a property-owner mailing address; false = only those that do not. Coverage varies sharply by jurisdiction (we hold the county assessor roll for some and not others), so this is a targeting filter rather than a defect: it returns exactly the rows that are actionable. The address itself is visible on Business and above."""

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    per_page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 25
    r"""Results per page. Above your plan's maximum this is clamped, not rejected; the response echoes the per_page actually applied."""

    keyword: Annotated[
        OptionalNullable[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `q`."""

    date_from: Annotated[
        OptionalNullable[date],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `date_after`."""

    date_to: Annotated[
        OptionalNullable[date],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `date_before`."""

    start_date: Annotated[
        OptionalNullable[date],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `date_after`."""

    end_date: Annotated[
        OptionalNullable[date],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `date_before`."""

    limit: Annotated[
        OptionalNullable[int],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Alias of `per_page`. Clamped to your plan's maximum, not rejected."""

    count_only: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Return only the total for these filters -- no permit records. Skips the row fetch entirely, so it is markedly cheaper for both of us when you are sizing a query rather than reading it. `results` comes back empty and `total_capped` / `total_unknown` mean exactly what they always do."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "zip_code",
                "city",
                "state",
                "jurisdiction",
                "address",
                "lat",
                "lng",
                "radius_miles",
                "fields",
                "bbox",
                "polygon",
                "category",
                "status",
                "property_type",
                "tag",
                "record_kind",
                "filed_after",
                "filed_before",
                "issued_after",
                "issued_before",
                "date_after",
                "date_before",
                "parcel",
                "min_value",
                "max_value",
                "min_solar_kw",
                "max_solar_kw",
                "min_sqft",
                "has_enrichment",
                "scope",
                "q",
                "contractor_name",
                "owner_filed",
                "has_owner_address",
                "page",
                "per_page",
                "keyword",
                "date_from",
                "date_to",
                "start_date",
                "end_date",
                "limit",
                "count_only",
            ]
        )
        nullable_fields = set(
            [
                "zip_code",
                "city",
                "state",
                "jurisdiction",
                "address",
                "lat",
                "lng",
                "bbox",
                "polygon",
                "category",
                "status",
                "property_type",
                "tag",
                "filed_after",
                "filed_before",
                "issued_after",
                "issued_before",
                "date_after",
                "date_before",
                "parcel",
                "min_value",
                "max_value",
                "min_solar_kw",
                "max_solar_kw",
                "min_sqft",
                "has_enrichment",
                "scope",
                "q",
                "contractor_name",
                "owner_filed",
                "has_owner_address",
                "keyword",
                "date_from",
                "date_to",
                "start_date",
                "end_date",
                "limit",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
