"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import BaseModel
from permitstack.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class UpdateWebhookRequestTypedDict(TypedDict):
    webhook_id: str
    is_active: bool
    r"""true re-activates a webhook the failure breaker switched off."""


class UpdateWebhookRequest(BaseModel):
    webhook_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    is_active: Annotated[
        bool, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""true re-activates a webhook the failure breaker switched off."""
