"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from permitstack.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class WebhookCreateTypedDict(TypedDict):
    url: str
    city: NotRequired[Nullable[str]]
    state: NotRequired[Nullable[str]]
    category: NotRequired[Nullable[str]]
    zip_code: NotRequired[Nullable[str]]
    keyword: NotRequired[Nullable[str]]
    contractor_name: NotRequired[Nullable[str]]
    r"""Fire only for permits pulled by contractors whose name contains this text (case-insensitive) — track a competitor or partner as their new permits arrive."""


class WebhookCreate(BaseModel):
    url: str

    city: OptionalNullable[str] = UNSET

    state: OptionalNullable[str] = UNSET

    category: OptionalNullable[str] = UNSET

    zip_code: OptionalNullable[str] = UNSET

    keyword: OptionalNullable[str] = UNSET

    contractor_name: OptionalNullable[str] = UNSET
    r"""Fire only for permits pulled by contractors whose name contains this text (case-insensitive) — track a competitor or partner as their new permits arrive."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["city", "state", "category", "zip_code", "keyword", "contractor_name"]
        )
        nullable_fields = set(
            ["city", "state", "category", "zip_code", "keyword", "contractor_name"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
